language: go

go:
  - 1.14.x

os:
  - linux

services:
  - docker

before_script:
  - go get -v golang.org/x/lint/golint
  - env GOOS=linux go build ./src/cmd/accountd
  - docker build -t jenkins/accountd:latest -f ./src/cmd/accountd/DockerfileTravis .

script:
  - go test ./src/internal/...
  - go test ./src/cmd/accountd/handlers/...

after_script:
  - docker rmi jenkins/accountd:latest

notifications:
  # Get email notifications on builds (sent to email associated with Travis account)
  email:
    on_success: always
    on_failure: always
