language: go

go:
  - 1.14.x

os:
  - linux

services:
  - mysql

before_script:
  - go get -v golang.org/x/lint/golint
  - env CGO_ENABLED=0 GOOS=linux go build  -a -ldflags="-extldflags=-static" $TRAVIS_BUILD_DIR/cmd/accountd

script:
  - go test ./... -v

notifications:
  # Get email notifications on builds (sent to email associated with Travis account)
  email:
    on_success: always
    on_failure: always
