### Copyright (c) 2020 Richard Youngkin. All rights reserved.
### Use of this source code is governed by a MIT-style
### license that can be found in the LICENSE file.

apiVersion: v1
kind: ConfigMap
metadata:
  name: custd-server-conf
  labels:
{{ include "customerd.labels" . | indent 4 }}
data:
  config: |
    port={{ .Values.customerd.port }}
    logLevel={{ .Values.customerd.logLevel }}
    dbHost={{ .Values.customerd.dbHost }}
    dbPort={{ .Values.customerd.dbPort }}
    dbName={{ .Values.customerd.dbName }}
 