secrets:
    dbuser: ENC[AES256_GCM,data:hoqeUpA=,iv:qwK054sQwcR7tgLf7/corXa2fZf4mxmd08+pxkOgtj8=,tag:OC8r4t4NHaB5rz4a/MpHpg==,type:str]
    dbpassword: ENC[AES256_GCM,data:t6Q+0aA=,iv:QudWCiyjuLtKy8WQSHRwCuMd11FgZh0WYRKbgZK6hXk=,tag:Re90OzT+6wGaZrKQl0UHhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-13T23:28:45Z'
    mac: ENC[AES256_GCM,data:OS555YHsZe+Gk0zGlClQQ+batO3ysbvjU+qfB8m+NxGPzUYXW3HUIPjWbQ4kPKnYrBlW5orDm6S4X/zLpg9O0BzF0O73Hglr5iSVEfk75EWi4eE0bZ0KQ7m6EwkLaadj56DC7fVCXouo2myDkz7qpSPRFmLuBErXA8YWntksr3o=,iv:97S6XiZjghHu1PPUDvALItzQG4m0khsaWcUrLTCQNKQ=,tag:ihM4z5JNSX2aby+cIJuRmQ==,type:str]
    pgp:
    -   created_at: '2020-02-12T21:49:14Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAyf6MfK70NBiAQf/fZlDBdB1ZqxpQ5Yr/skRp0G2fOR2bmkBaw/Cu+e7b9P1
            zkW3wPglES5zql3HugI5ODrREkuW0qTksYSjlWEXVSUuI387AsFTCURqfy4M/OaG
            Hz5wXS+c210LaVcqcM1nswnetV7Hi01nL3W6oqlfLfhFkiOJGQqd1FETr58U/Ts3
            y/skO/8ew5otYK4WLNFazy1e455d0ETDKFdFgfyy7WA8NQpr+6rbImHuBPBZ+00m
            pJq/P8CsDCOzhkXpTB0wElI2xN6d4FtYDPT5ift+RVx4YxazplWbH2Pw4AY44Rae
            h86eCKi1ekNZVIZpjZTuLKJJo+cZa+UUc7/1sxV3j9JcAe0JD+VuWkS0H7O5PFD5
            S4ImSYVpHUDNAo90yJFAKEJAb0WUZUEXpCSnToZ41HXAPto74kHoGnTTYoa1Q2y1
            8LRwW/hK4rVQ9d7L4JlFqKTxxZSww2k7/GPpH54=
            =ocpp
            -----END PGP MESSAGE-----
        fp: 57BE572E89ECA7360D3F68BFA258CF386C55D02E
    unencrypted_suffix: _unencrypted
    version: 3.5.0
