DROP DATABASE IF EXISTS mockvideo;
CREATE DATABASE mockvideo;

USE mockvideo;

DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
    id INT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
)