# Default values for mockvideo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: ryoungkin/customerd
  tag: 0.0.6
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# If want to use these settings, uncomment, override values as necessary, and remove the curly-braces on 'annotations'
# Use the below commented-out 'annotations' instead of the uncommented one
#annotations: {}
annotations: {
  prometheusIOScrape: "true",
  prometheusIOPort: "5000",
  prometheusIOPath: "/metrics"
}

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: custd.kube
      paths: [/customers,/custdhealth,/metrics]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

customerd:
  port: "5999"
