### Copyright (c) 2020 Richard Youngkin. All rights reserved.
### Use of this source code is governed by a MIT-style
### license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysqlService.name }}
  labels:
{{ include "mockvideo.labels" . | indent 4 }}
spec:
  type: {{ .Values.mysqlService.type }}
  ports:
    - port: {{ .Values.mysqlService.port }}
      targetPort: {{ .Values.mysqlService.port }}
      protocol: TCP
      name: {{ .Values.mysqlService.name }}
  selector: {}
