### Copyright (c) 2020 Richard Youngkin. All rights reserved.
### Use of this source code is governed by a MIT-style
### license that can be found in the LICENSE file.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "accountd.fullname" . }}
  labels:
{{ include "accountd.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "accountd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
